---
- name: Debian VM Hardening
  hosts: your_vm_group
  become: yes
  tasks:
    - name: Update package cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Set user password policy
      debconf:
        name: passwd
        question: "passwd/password-quality"
        vtype: select
        value: 6

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Reload SSH

    - name: Set SSH protocol to 2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol'
        line: 'Protocol 2'
      notify: Reload SSH

  handlers:
    - name: Reload SSH
      service:
        name: ssh
        state: reloaded
