---
- name: Install Zabbix Agent2
  hosts: new
  become: True
  tasks:

    - name: Install Zabbix Agent
      yum:

        name: http://x.x.x.x/package/zabbix-agent2-5.0.12-1.el7.x86_64.rpm


    - name: Add Zabbix Server IP
      lineinfile:

        path: /etc/zabbix/zabbix_agent2.conf

        regexp: '^Server='

        line: 'Server=zabbix-server'


    - name: Disable Zabbix ServerActive
      lineinfile:

        path: /etc/zabbix/zabbix_agent2.conf

        regexp: '^ServerActive='

        line: '#'


    - name: Add Zabbix Agent Hostname
      lineinfile:

        path: /etc/zabbix/zabbix_agent2.conf

        regexp: '^Hostname='

        line: 'Hostname=system.hostname'


    - name: Enable and Start ZabbixAgent Service
      systemd:
        name: zabbix-agent2
        enabled: yes
        state: restarted
